helmDefaults:
  historyMax: 10
  verify: false
  wait: false
  timeout: 600
  recreatePods: false
  force: false
  createNamespace: false

repositories:
  - name: aza
    url: https://{{ requiredEnv "GITHUB_TOKEN"}}@raw.githubusercontent.com/bitpesa/bitpesa-terraform/master/helm-charts

environments:
  default: {}
  staging: {}
  testing: {}
  production: {}

releases:
  - chart: aza/microservice
    cleanupOnFail: false
    devel: false
    name: liquidity-request-service
    namespace: liquidity-request-service
    skipDeps: false
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl
