default: &default
  primary:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV['LIQUIDITY_REQUEST_SERVICE_DATABASE_HOST'] %>
    username: <%= ENV['LIQUIDITY_REQUEST_SERVICE_DATABASE_USERNAME'] %>
    password: <%= ENV['LIQUIDITY_REQUEST_SERVICE_DATABASE_PASSWORD'] %>
    database: <%= ENV['LIQUIDITY_REQUEST_SERVICE_DATABASE_NAME'] %>
    pool: <%= ENV.fetch("ADMIN_DATABASE_POOL") { 5 } %>
  aza_admin:
    adapter: postgresql
    encoding: "utf8"
    reconnect: true
    secret: <%= ENV['ADMIN_DATABASE_SECRET'] %>
    pool: <%= ENV.fetch("ADMIN_DATABASE_POOL") { 5 } %>
    host: <%= ENV['ADMIN_DATABASE_HOST'] %>
    username: <%= ENV['ADMIN_DATABASE_USERNAME'] %>
    password: <%= ENV['ADMIN_DATABASE_PASSWORD'] %>
    database: <%= ENV['ADMIN_DATABASE_NAME'] %>
    database_tasks: false
  aza_api:
    adapter: postgresql
    encoding: "utf8"
    reconnect: true
    secret: <%= ENV['API_DATABASE_SECRET'] %>
    pool: <%= ENV.fetch("API_DATABASE_POOL") { 5 } %>
    host: <%= ENV['API_DATABASE_HOST'] %>
    username: <%= ENV['API_DATABASE_USERNAME'] %>
    password: <%= ENV['API_DATABASE_PASSWORD'] %>
    database: <%= ENV['API_DATABASE_NAME'] %>
    database_tasks: false

development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
